(() => {
  const SCHEMA_VERSION = 1;
  const STORAGE_KEY = 'newlywedHomeManager:v1';
  const ROOMS = ['거실','주방/식당','침실2','욕실','현관','발코니','세탁기 공간','실외기 공간','기타'];
  const TYPES = ['가전','가구','생활용품'];
  const PRIORITIES = ['1순위 필수 구매','2순위 구매 예정','3순위 고민 중','4순위 나중 구매','5순위 구매 제외'];
  const STATUSES = ['후보 조사','견적 확인','구매 고민','최종 선택','결제 완료','배송 예정','설치 완료'];
  const INSTALL_STATUSES = ['실측 필요','설치 가능','설치 어려움','설치 불가'];
  const PAYMENT_METHODS = ['미지정','현금','계좌이체','신용카드','체크카드','상품권','포인트','복합결제'];
  const PAYER_TYPES = ['미지정','나','배우자','공동 부담'];
  const navItems = [
    ['dashboard','⌂','대시보드'],['products','▦','제품 목록'],['appliances','◫','가전'],['furniture','▤','가구'],
    ['rooms','⌑','방별 보기'],['floorplan','⌗','우리집 평면도'],['compare','⇄','제품 비교'],['quotes','₩','견적 비교'],
    ['checklist','✓','체크리스트'],['schedule','◷','구매 일정'],['budget','▥','예산 분석'],['wishlist','♡','위시리스트'],['settings','⚙','설정']
  ];

  const sampleProducts = [
    {id:uid(),type:'가전',category:'냉장고',name:'냉장고',brand:'예시 브랜드',model:'SAMPLE-RF',image:'',url:'',store:'',roomId:'주방/식당',listPrice:3200000,quotePrice:2900000,expectedPrice:2800000,actualPrice:0,quantity:1,storeDiscount:0,brandDiscount:0,eventDiscount:0,cardDiscount:0,couponDiscount:0,pointsUsed:0,cashback:0,giftValue:0,giftIncluded:false,priority:'1순위 필수 구매',purchaseStatus:'후보 조사',purchasePlanDate:'',purchaseDate:'',deliveryDate:'',installDate:'',deliveryDone:false,installDone:false,paymentMethod:'미지정',cardCompany:'',cardName:'',installmentMonths:0,payerType:'미지정',mySharePercent:50,partnerSharePercent:50,widthMm:0,depthMm:0,heightMm:0,installStatus:'실측 필요',favorite:false,memo:'예시 데이터',isSample:true},
    {id:uid(),type:'가구',category:'소파',name:'3인용 소파',brand:'예시 브랜드',model:'SAMPLE-SOFA',image:'',url:'',store:'',roomId:'거실',listPrice:2600000,quotePrice:2300000,expectedPrice:2200000,actualPrice:0,quantity:1,storeDiscount:0,brandDiscount:0,eventDiscount:0,cardDiscount:0,couponDiscount:0,pointsUsed:0,cashback:0,giftValue:0,giftIncluded:false,priority:'2순위 구매 예정',purchaseStatus:'구매 고민',purchasePlanDate:'',purchaseDate:'',deliveryDate:'',installDate:'',deliveryDone:false,installDone:false,paymentMethod:'미지정',cardCompany:'',cardName:'',installmentMonths:0,payerType:'공동 부담',mySharePercent:50,partnerSharePercent:50,widthMm:2800,depthMm:1000,heightMm:850,installStatus:'실측 필요',favorite:true,memo:'예시 데이터',isSample:true}
  ];

  const defaultState = () => ({
    schemaVersion: SCHEMA_VERSION,
    project:{id:'home-1',name:'우리 신혼집',totalBudget:20000000,moveInDate:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
    products: sampleProducts,
    quotes:[],
    checklist:[
      {id:uid(),title:'냉장고장 크기 측정',roomId:'주방/식당',productId:'',completed:false},
      {id:uid(),title:'소파 벽면 길이 측정',roomId:'거실',productId:'',completed:false}
    ],
    schedule:[], wishlist:[], floorPlanItems:[],
    categories:{가전:['TV','냉장고','김치냉장고','세탁기','건조기','워시타워','에어컨','청소기','로봇청소기','공기청정기','제습기','식기세척기','인덕션','전자레인지','오븐','에어프라이어','전기밥솥','커피머신','정수기','비데','음식물처리기','기타'],가구:['침대','매트리스','소파','식탁','식탁의자','거실장','TV장','화장대','협탁','옷장','붙박이장','서랍장','책상','책장','수납장','신발장','커튼','블라인드','조명','러그','기타'],생활용품:['주방용품','욕실용품','침구','청소용품','기타']},
    settings:{sampleData:true,autoSave:true,lastSavedAt:new Date().toISOString()}
  });

  let state = loadState();
  let ui = {view:'dashboard',search:'',typeFilter:'전체',statusFilter:'전체',modal:null,editingId:null,selectedCompare:[],selectedFloorItem:null,toast:'',quoteEdit:null};
  const app = document.getElementById('app');

  function uid(){return (crypto?.randomUUID?.() || ('id-'+Date.now()+'-'+Math.random().toString(36).slice(2)));}
  function num(v){const n=Number(String(v ?? '').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
  function won(v){return `${Math.round(num(v)).toLocaleString('ko-KR')}원`}
  function pct(v){return `${Math.max(0,Math.min(100,Math.round(v)))}%`}
  function esc(s){return String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function dateLabel(d){if(!d)return '-'; const x=new Date(d+'T00:00:00'); return isNaN(x)?'-':`${x.getMonth()+1}/${x.getDate()}`}
  function isPurchased(p){return ['결제 완료','배송 예정','설치 완료'].includes(p.purchaseStatus) || num(p.actualPrice)>0}
  function calcActualTotal(p){return Math.max(0,num(p.actualPrice)*Math.max(1,num(p.quantity)||1))}
  function calcExpectedTotal(p){return Math.max(0,num(p.expectedPrice)*Math.max(1,num(p.quantity)||1))}
  function calcEffective(p){let v=calcActualTotal(p)-num(p.cashback)-num(p.pointsUsed); if(p.giftIncluded) v-=num(p.giftValue); return Math.max(0,v)}
  function calcSaving(p){return calcExpectedTotal(p)-calcActualTotal(p)}
  function calcListDiscount(p){return Math.max(0,num(p.listPrice)*Math.max(1,num(p.quantity)||1)-calcActualTotal(p))}
  function totals(){
    const expected=state.products.filter(p=>p.priority!=='5순위 구매 제외').reduce((s,p)=>s+calcExpectedTotal(p),0);
    const actual=state.products.filter(isPurchased).reduce((s,p)=>s+calcActualTotal(p),0);
    const effective=state.products.filter(isPurchased).reduce((s,p)=>s+calcEffective(p),0);
    const purchased=state.products.filter(isPurchased).length;
    const savings=state.products.filter(isPurchased).reduce((s,p)=>s+Math.max(0,calcSaving(p)),0);
    const over=state.products.filter(isPurchased).reduce((s,p)=>s+Math.max(0,-calcSaving(p)),0);
    let mine=0,partner=0,unassigned=0;
    state.products.filter(isPurchased).forEach(p=>{const cost=calcActualTotal(p);if(p.payerType==='나')mine+=cost;else if(p.payerType==='배우자')partner+=cost;else if(p.payerType==='공동 부담'){mine+=cost*(num(p.mySharePercent)/100);partner+=cost*(num(p.partnerSharePercent)/100)}else unassigned+=cost});
    return {expected,actual,effective,remaining:num(state.project.totalBudget)-actual,purchased,total:state.products.length,savings,over,mine,partner,unassigned};
  }
  function roomTotals(){return ROOMS.map(r=>({room:r,total:state.products.filter(p=>p.roomId===r&&isPurchased(p)).reduce((s,p)=>s+calcActualTotal(p),0),expected:state.products.filter(p=>p.roomId===r).reduce((s,p)=>s+calcExpectedTotal(p),0),count:state.products.filter(p=>p.roomId===r).length,purchased:state.products.filter(p=>p.roomId===r&&isPurchased(p)).length}));}
  function saveState(){state.project.updatedAt=new Date().toISOString();state.settings.lastSavedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return defaultState();const parsed=JSON.parse(raw);return migrate(parsed)}catch(e){console.error(e);return defaultState()}}
  function migrate(data){if(!data || typeof data!=='object') return defaultState(); if(!data.schemaVersion)data.schemaVersion=1; const base=defaultState(); return {...base,...data,project:{...base.project,...data.project},settings:{...base.settings,...data.settings},categories:{...base.categories,...(data.categories||{})},products:Array.isArray(data.products)?data.products:[],quotes:Array.isArray(data.quotes)?data.quotes:[],checklist:Array.isArray(data.checklist)?data.checklist:[],schedule:Array.isArray(data.schedule)?data.schedule:[],wishlist:Array.isArray(data.wishlist)?data.wishlist:[],floorPlanItems:Array.isArray(data.floorPlanItems)?data.floorPlanItems:[]};}
  function commit(message='저장됨'){saveState();render();toast(message)}
  function toast(message){ui.toast=message;renderToast();setTimeout(()=>{ui.toast='';renderToast()},1600)}
  function renderToast(){document.querySelectorAll('.toast').forEach(x=>x.remove());if(ui.toast){const d=document.createElement('div');d.className='toast';d.textContent=ui.toast;document.body.appendChild(d)}}

  function render(){
    const current=navItems.find(n=>n[0]===ui.view) || navItems[0];
    app.innerHTML=`<div class="app-shell">
      <aside class="sidebar"><div class="brand"><div class="brand-logo">⌂</div><div><h1>우리집 준비노트</h1><small>${esc(state.project.name)}</small></div></div>
        <nav class="nav">${navItems.map(([id,ic,label])=>`<button data-view="${id}" class="${ui.view===id?'active':''}"><span>${ic}</span>${label}</button>`).join('')}</nav>
        <div class="sidebar-foot">자동 저장 · schema v${state.schemaVersion}<br>${state.settings.lastSavedAt?new Date(state.settings.lastSavedAt).toLocaleString('ko-KR'):''}</div></aside>
      <main class="main"><header class="topbar"><div><h2>${current[2]}</h2><p>${subtitle(ui.view)}</p></div><div class="actions"><button class="btn" id="quickBackup">백업</button><button class="btn primary" id="addProductTop">+ 제품 추가</button></div></header>${viewContent()}</main>
      ${mobileNav()}<button class="fab" id="fabAdd">+</button>
    </div>${modalContent()}`;
    bindCommon(); bindView(); renderToast();
  }
  function subtitle(v){return ({dashboard:'예산·구매·입주 준비 상태를 한눈에 확인합니다.',products:'가전·가구·생활용품을 한 곳에서 관리합니다.',appliances:'등록된 가전만 빠르게 확인합니다.',furniture:'등록된 가구만 빠르게 확인합니다.',rooms:'공간별 제품·지출·진행률을 확인합니다.',floorplan:'원본 평면도를 보존한 채 제품을 별도 레이어로 배치합니다.',compare:'후보 제품을 최대 5개까지 나란히 비교합니다.',quotes:'매장·브랜드별 견적을 저장하고 체감가를 비교합니다.',checklist:'구매 및 실측 할 일을 관리합니다.',schedule:'견적·구매·배송·설치 일정을 관리합니다.',budget:'예산 대비 지출과 분담 구조를 분석합니다.',wishlist:'당장 구매하지 않는 후보를 따로 모아둡니다.',settings:'프로젝트 정보·백업·복구·초기화를 관리합니다.'}[v]||'');}
  function mobileNav(){const items=[['dashboard','⌂','홈'],['products','▦','목록'],['products','＋','추가'],['budget','₩','예산'],['settings','•••','더보기']];return `<nav class="mobile-nav">${items.map((x,i)=>`<button data-mobile="${i}" data-view="${x[0]}" class="${ui.view===x[0]&&i!==2?'active':''}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
  function bindCommon(){
    document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',e=>{if(e.currentTarget.dataset.mobile==='2'){openProduct();return}ui.view=e.currentTarget.dataset.view;ui.search='';render()}));
    document.getElementById('addProductTop')?.addEventListener('click',()=>openProduct()); document.getElementById('fabAdd')?.addEventListener('click',()=>openProduct());
    document.getElementById('quickBackup')?.addEventListener('click',exportJSON);
    document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>{ui.modal=null;ui.editingId=null;render()}));
  }

  function viewContent(){switch(ui.view){case'dashboard':return dashboard();case'products':return productsView();case'appliances':return productsView('가전');case'furniture':return productsView('가구');case'rooms':return roomsView();case'floorplan':return floorplanView();case'compare':return compareView();case'quotes':return quotesView();case'checklist':return checklistView();case'schedule':return scheduleView();case'budget':return budgetView();case'wishlist':return wishlistView();case'settings':return settingsView();default:return dashboard()}}

  function dashboard(){const t=totals();const progress=t.total?100*t.purchased/t.total:0;const moveIn=state.project.moveInDate?Math.ceil((new Date(state.project.moveInDate+'T00:00:00')-new Date())/86400000):null;const upcoming=state.schedule.slice().sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>!x.date||new Date(x.date+'T23:59:59')>=new Date()).slice(0,5);const essentials=state.products.filter(p=>p.priority==='1순위 필수 구매'&&!isPurchased(p));return `
    <div class="grid metrics">
      ${metric('전체 혼수 예산',won(state.project.totalBudget),'프로젝트 기준')}${metric('현재 실제 지출',won(t.actual),`${Math.round(t.actual/Math.max(1,num(state.project.totalBudget))*100)}% 사용`)}${metric('남은 예산',won(t.remaining),t.remaining<0?`예산 ${won(-t.remaining)} 초과`:'사용 가능 금액',t.remaining<0)}${metric('구매 진행률',`${t.purchased} / ${t.total}개`,pct(progress))}
    </div>
    <div class="section split"><div class="card"><div class="section-title"><h3>예산 진행 상황</h3><span class="hint">실제 결제금액 기준</span></div><div class="progress"><span style="width:${Math.min(100,Math.max(0,t.actual/Math.max(1,num(state.project.totalBudget))*100))}%"></span></div>
      <div class="kpi-line"><span>예상 총금액</span><strong>${won(t.expected)}</strong></div><div class="kpi-line"><span>최종 체감 구매금액</span><strong>${won(t.effective)}</strong></div><div class="kpi-line"><span>총 절약 금액</span><strong>${won(t.savings)}</strong></div><div class="kpi-line"><span>총 초과 금액</span><strong>${won(t.over)}</strong></div>
      ${t.remaining<0?`<div class="notice danger-note">현재 예산을 ${won(-t.remaining)} 초과했습니다.</div>`:''}</div>
      <div class="card"><div class="section-title"><h3>입주 준비</h3></div>${state.project.moveInDate?`<div class="metric"><div class="label">입주 예정일</div><div class="value">${moveIn>=0?'D-'+moveIn:'입주일 경과'}</div><div class="sub">${esc(state.project.moveInDate)}</div></div>`:`<div class="empty"><strong>입주일을 설정해 주세요</strong><span>설정에서 입주 예정일을 입력하면 D-Day가 표시됩니다.</span></div>`}</div></div>
    <div class="section split"><div class="card"><div class="section-title"><h3>아직 준비하지 않은 필수품</h3><span class="hint">${essentials.length}개</span></div><div class="mini-list">${essentials.length?essentials.slice(0,6).map(p=>`<div class="mini-item"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.roomId||'공간 미지정')}</div></div><span class="badge warn">${esc(p.purchaseStatus)}</span></div>`).join(''):'<div class="empty"><strong>필수품 준비가 완료되었습니다</strong></div>'}</div></div>
      <div class="card"><div class="section-title"><h3>앞으로 해야 할 일</h3><span class="hint">일정 ${upcoming.length}개</span></div><div class="mini-list">${upcoming.length?upcoming.map(s=>`<div class="mini-item"><div><strong>${esc(s.title)}</strong><div class="muted">${esc(s.type)} · ${dateLabel(s.date)}</div></div></div>`).join(''):'<div class="empty"><strong>예정된 일정이 없습니다</strong><span>구매 일정 메뉴에서 추가할 수 있습니다.</span></div>'}</div></div></div>
    <div class="section card"><div class="section-title"><h3>최근 구매 제품</h3><button class="btn ghost" data-view="products">전체 보기</button></div>${productTable(state.products.filter(isPurchased).slice(-5).reverse())}</div>`}
  function metric(label,value,sub,alert=false){return `<div class="card metric ${alert?'alert':''}"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub||''}</div></div>`}

  function productsView(forcedType){let list=state.products.slice();const type=forcedType||ui.typeFilter;if(type&&type!=='전체')list=list.filter(p=>p.type===type);if(ui.statusFilter!=='전체')list=list.filter(p=>p.purchaseStatus===ui.statusFilter);if(ui.search){const q=ui.search.toLowerCase();list=list.filter(p=>[p.name,p.brand,p.model,p.category,p.roomId].some(x=>String(x||'').toLowerCase().includes(q)))}return `<div class="toolbar"><input id="searchInput" value="${esc(ui.search)}" placeholder="제품명·브랜드·모델명 검색">${forcedType?'':`<select id="typeFilter"><option>전체</option>${TYPES.map(x=>`<option ${ui.typeFilter===x?'selected':''}>${x}</option>`).join('')}</select>`}<select id="statusFilter"><option>전체</option>${STATUSES.map(x=>`<option ${ui.statusFilter===x?'selected':''}>${x}</option>`).join('')}</select><span class="muted">${list.length}개</span></div><div class="card" style="padding:0">${productTable(list)}</div>`}
  function productTable(list){if(!list.length)return `<div class="empty"><strong>아직 등록된 제품이 없습니다.</strong><span>+ 제품 추가 버튼으로 첫 제품을 등록해 보세요.</span></div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>사진</th><th>구분</th><th>제품</th><th>브랜드</th><th>예상가격</th><th>실제가격</th><th>체감가격</th><th>차액</th><th>우선순위</th><th>구매상태</th><th>설치 공간</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td>${p.image?`<img class="thumb" src="${esc(p.image)}">`:`<div class="thumb"></div>`}</td><td>${esc(p.type)}</td><td><strong>${esc(p.name)}</strong>${p.isSample?' <span class="badge warn">예시 데이터</span>':''}<div class="muted">${esc(p.model||'')}</div></td><td>${esc(p.brand||'-')}</td><td>${won(calcExpectedTotal(p))}</td><td>${won(calcActualTotal(p))}</td><td>${won(calcEffective(p))}</td><td>${calcSaving(p)>=0?`<span class="badge ok">${won(calcSaving(p))} 절약</span>`:`<span class="badge danger">${won(-calcSaving(p))} 초과</span>`}</td><td><span class="badge">${esc(p.priority)}</span></td><td><span class="badge ${isPurchased(p)?'ok':''}">${esc(p.purchaseStatus)}</span></td><td>${esc(p.roomId||'-')}</td><td><button class="btn ghost edit-product" data-id="${p.id}">수정</button></td></tr>`).join('')}</tbody></table></div>`}

  function roomsView(){return `<div class="room-grid">${roomTotals().map(r=>`<div class="card room-card"><div class="section-title"><h3>${esc(r.room)}</h3><span class="badge">${r.purchased}/${r.count}</span></div><div class="kpi-line"><span>예상 예산</span><strong>${won(r.expected)}</strong></div><div class="kpi-line"><span>실제 지출</span><strong>${won(r.total)}</strong></div><div class="progress"><span style="width:${r.count?100*r.purchased/r.count:0}%"></span></div><div class="muted" style="margin-top:8px">준비율 ${r.count?pct(100*r.purchased/r.count):'0%'}</div></div>`).join('')}</div>`}

  function compareView(){const eligible=state.products;const selected=ui.selectedCompare.map(id=>state.products.find(p=>p.id===id)).filter(Boolean);return `<div class="toolbar"><select id="comparePicker"><option value="">비교할 제품 선택</option>${eligible.filter(p=>!ui.selectedCompare.includes(p.id)).map(p=>`<option value="${p.id}">${esc(p.category)} · ${esc(p.name)} · ${esc(p.brand||'브랜드 미정')}</option>`).join('')}</select><button class="btn" id="addCompare">추가</button><span class="muted">최대 5개</span></div>${selected.length?`<div class="compare-grid">${selected.map(p=>`<div class="card compare-card">${p.image?`<img src="${esc(p.image)}">`:''}<div class="section-title"><h3>${esc(p.name)}</h3><button class="btn ghost remove-compare" data-id="${p.id}">✕</button></div>${[['브랜드',p.brand||'-'],['모델명',p.model||'-'],['예상가',won(calcExpectedTotal(p))],['실구매가',won(calcActualTotal(p))],['체감가',won(calcEffective(p))],['크기',p.widthMm?`${p.widthMm} × ${p.depthMm} × ${p.heightMm}mm`:'미등록'],['공간',p.roomId||'-'],['설치상태',p.installStatus||'실측 필요'],['메모',p.memo||'-']].map(x=>`<div class="compare-row"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div>`).join('')}</div>`:`<div class="card empty"><strong>비교할 제품을 선택해 주세요.</strong><span>같은 카테고리 후보를 3~5개 나란히 비교하면 편리합니다.</span></div>`}`}

  function quotesView(){return `<div class="section-title"><h3>등록된 견적 ${state.quotes.length}건</h3><button class="btn primary" id="addQuote">+ 견적 등록</button></div>${state.quotes.length?`<div class="quote-grid">${state.quotes.map(q=>`<div class="card"><div class="section-title"><div><h3>${esc(q.name)}</h3><div class="muted">${esc(q.store||'매장 미지정')} · ${esc(q.date||'날짜 미지정')}</div></div><button class="btn ghost edit-quote" data-id="${q.id}">수정</button></div><div class="kpi-line"><span>정상가</span><strong>${won(q.normalPrice)}</strong></div><div class="kpi-line"><span>최종 결제금액</span><strong>${won(q.finalPrice)}</strong></div><div class="kpi-line"><span>체감 구매금액</span><strong>${won(q.effectivePrice)}</strong></div><div class="quote-products">${(q.productIds||[]).map(id=>state.products.find(p=>p.id===id)?.name).filter(Boolean).join(', ')||'포함 제품 미지정'}</div></div>`).join('')}</div>`:`<div class="card empty"><strong>아직 등록된 견적이 없습니다.</strong><span>삼성·LG·백화점·온라인몰 등 받은 견적을 비교해 보세요.</span></div>`}`}

  function checklistView(){const done=state.checklist.filter(x=>x.completed).length;return `<div class="section-title"><div><h3>${done} / ${state.checklist.length}개 완료</h3><div class="progress" style="width:220px;margin-top:8px"><span style="width:${state.checklist.length?done/state.checklist.length*100:0}%"></span></div></div><button class="btn primary" id="addChecklist">+ 할 일 추가</button></div><div class="check-grid">${ROOMS.map(room=>{const items=state.checklist.filter(x=>x.roomId===room);if(!items.length)return'';return `<div class="card"><h3>${esc(room)}</h3>${items.map(i=>`<div class="check-row ${i.completed?'done':''}"><input type="checkbox" class="check-toggle" data-id="${i.id}" ${i.completed?'checked':''}><span>${esc(i.title)}</span><button class="btn ghost delete-check" data-id="${i.id}" style="margin-left:auto">✕</button></div>`).join('')}</div>`}).join('')}</div>`}

  function scheduleView(){const list=state.schedule.slice().sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));return `<div class="section-title"><h3>구매·배송·설치 일정</h3><button class="btn primary" id="addSchedule">+ 일정 추가</button></div>${list.length?`<div class="calendar-list">${list.map(s=>`<div class="calendar-item"><strong>${esc(s.date||'날짜 미정')}</strong><span class="badge">${esc(s.type)}</span><div><strong>${esc(s.title)}</strong><div class="muted">${esc(s.memo||'')}</div></div><button class="btn ghost delete-schedule" data-id="${s.id}">삭제</button></div>`).join('')}</div>`:`<div class="card empty"><strong>등록된 일정이 없습니다.</strong><span>견적 방문, 구매, 배송, 설치 일정을 기록해 보세요.</span></div>`}`}

  function budgetView(){const t=totals();const byType=TYPES.map(type=>({name:type,value:state.products.filter(p=>p.type===type&&isPurchased(p)).reduce((s,p)=>s+calcActualTotal(p),0)}));const max=Math.max(1,...byType.map(x=>x.value));return `<div class="grid metrics">${metric('전체 예산',won(state.project.totalBudget),'설정에서 변경 가능')}${metric('실제 지출',won(t.actual),'결제 완료/실구매가 기준')}${metric('나의 부담',won(t.mine),'비용 분담 기준')}${metric('배우자 부담',won(t.partner),'비용 분담 기준')}</div><div class="section split"><div class="card"><div class="section-title"><h3>유형별 실제 지출</h3></div><div class="chart-bars">${byType.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar"><i style="width:${x.value/max*100}%"></i></div><strong>${won(x.value)}</strong></div>`).join('')}</div></div><div class="card"><div class="section-title"><h3>비용 분담</h3></div><div class="kpi-line"><span>나</span><strong>${won(t.mine)}</strong></div><div class="kpi-line"><span>배우자</span><strong>${won(t.partner)}</strong></div><div class="kpi-line"><span>미지정</span><strong>${won(t.unassigned)}</strong></div><div class="kpi-line"><span>부담 차액</span><strong>${won(Math.abs(t.mine-t.partner))}</strong></div></div></div><div class="section card"><div class="section-title"><h3>방별 지출</h3></div><div class="chart-bars">${roomTotals().filter(x=>x.total||x.expected).map(x=>`<div class="bar-row"><span>${esc(x.room)}</span><div class="bar"><i style="width:${x.total/Math.max(1,...roomTotals().map(r=>r.total))*100}%"></i></div><strong>${won(x.total)}</strong></div>`).join('')}</div></div>`}

  function wishlistView(){return `<div class="section-title"><h3>위시리스트 ${state.wishlist.length}개</h3><button class="btn primary" id="addWish">+ 위시 추가</button></div>${state.wishlist.length?`<div class="wish-grid">${state.wishlist.map(w=>`<div class="card"><div class="section-title"><h3>${esc(w.name)}</h3><button class="btn ghost delete-wish" data-id="${w.id}">✕</button></div><div class="kpi-line"><span>희망가격</span><strong>${won(w.targetPrice)}</strong></div><div class="muted">${esc(w.memo||'')}</div></div>`).join('')}</div>`:`<div class="card empty"><strong>위시리스트가 비어 있습니다.</strong><span>커피머신, 스마트 조명처럼 나중에 살 제품을 저장해 두세요.</span></div>`}`}

  function floorplanView(){const placed=state.floorPlanItems.map(i=>({...i,product:state.products.find(p=>p.id===i.productId)})).filter(x=>x.product);return `<div class="floor-wrap"><div class="floor-stage"><div class="floor-canvas" id="floorCanvas"><img src="assets/home-floorplan.png" alt="우리집 원본 평면도">${placed.map(i=>`<div class="floor-item ${ui.selectedFloorItem===i.id?'selected':''}" data-floor-id="${i.id}" style="left:${i.x*100}%;top:${i.y*100}%;width:${i.width*100}%;height:${i.height*100}%;transform:translate(-50%,-50%) rotate(${i.rotation||0}deg)">${esc(i.product.name)}</div>`).join('')}</div></div><aside class="floor-side card"><div class="section-title"><h3>배치 모드</h3><span class="badge">${placed.length}개 배치</span></div><div class="notice">원본 평면도는 Base Layer로 고정하고 제품만 별도 Overlay Layer에 배치합니다.</div><div style="margin-top:14px">${state.products.map(p=>`<div class="product-pick"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.roomId||'공간 미지정')}</div></div><button class="btn add-floor-product" data-id="${p.id}">배치</button></div>`).join('')}</div>${ui.selectedFloorItem?`<div class="floor-controls"><button class="btn" id="rotateFloor">90° 회전</button><button class="btn danger" id="removeFloor">배치 제거</button></div>`:''}</aside></div>`}

  function settingsView(){return `<div class="split"><div class="card"><div class="section-title"><h3>프로젝트 설정</h3></div><div class="form-grid"><div class="field full"><label>프로젝트 이름</label><input id="projectName" value="${esc(state.project.name)}"></div><div class="field"><label>전체 혼수 예산</label><input id="projectBudget" inputmode="numeric" value="${num(state.project.totalBudget)}"></div><div class="field"><label>입주 예정일</label><input id="moveInDate" type="date" value="${esc(state.project.moveInDate||'')}"></div></div><div style="margin-top:14px"><button class="btn primary" id="saveSettings">저장</button></div></div><div class="card"><div class="section-title"><h3>데이터 관리</h3></div><div class="settings-list"><div class="setting-row"><div><strong>JSON 전체 백업</strong><div class="muted">제품·견적·일정·평면도 배치 포함</div></div><button class="btn" id="exportJson">내보내기</button></div><div class="setting-row"><div><strong>CSV 제품 내보내기</strong><div class="muted">Excel에서 열 수 있는 UTF-8 CSV</div></div><button class="btn" id="exportCsv">CSV</button></div><div class="setting-row"><div><strong>JSON 복구</strong><div class="muted">기존 데이터는 가져온 백업으로 대체됩니다.</div></div><label class="btn">가져오기<input id="importJson" type="file" accept="application/json" hidden></label></div><div class="setting-row"><div><strong>예시 데이터 삭제</strong><div class="muted">첫 실행용 샘플 제품만 제거합니다.</div></div><button class="btn" id="removeSamples">예시 삭제</button></div><div class="setting-row"><div><strong>전체 초기화</strong><div class="muted">2단계 확인 후 모든 로컬 데이터를 삭제</div></div><button class="btn danger" id="resetAll">초기화</button></div></div></div></div><div class="section card"><div class="section-title"><h3>사용자 카테고리</h3></div><div class="toolbar"><select id="catType">${TYPES.map(x=>`<option>${x}</option>`).join('')}</select><input id="newCategory" placeholder="새 카테고리 이름"><button class="btn" id="addCategory">추가</button></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr))">${TYPES.map(t=>`<div><strong>${t}</strong><div style="margin-top:8px;display:flex;gap:6px;flex-wrap:wrap">${(state.categories[t]||[]).map(c=>`<span class="badge">${esc(c)} <button class="delete-cat" data-type="${t}" data-cat="${esc(c)}" style="border:0;background:transparent">×</button></span>`).join('')}</div></div>`).join('')}</div></div><div class="section card"><div class="section-title"><h3>저장 정보</h3></div><div class="kpi-line"><span>저장 방식</span><strong>브라우저 LocalStorage</strong></div><div class="kpi-line"><span>스키마 버전</span><strong>${state.schemaVersion}</strong></div><div class="kpi-line"><span>마지막 저장</span><strong>${new Date(state.settings.lastSavedAt).toLocaleString('ko-KR')}</strong></div><div class="notice">현재 버전은 로그인 없이 이 브라우저에 저장됩니다. 다른 기기 공동 편집은 추후 Supabase/Firebase 등으로 확장 가능한 데이터 구조를 전제로 했습니다.</div></div>`}

  function modalContent(){if(!ui.modal)return'';if(ui.modal==='product')return productModal();if(ui.modal==='quote')return quoteModal();if(ui.modal==='simple')return simpleModal();return''}
  function productModal(){const p=state.products.find(x=>x.id===ui.editingId)||blankProduct();const cats=state.categories[p.type]||[];return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${ui.editingId?'제품 수정':'제품 등록'}</h3><button class="btn ghost" data-close-modal>✕</button></div><form id="productForm"><div class="modal-body"><div class="form-grid">
    ${fieldSelect('구분','type',p.type,TYPES)}${fieldSelect('카테고리','category',p.category,cats)}${fieldText('제품명','name',p.name,true)}${fieldText('브랜드','brand',p.brand)}${fieldText('모델명','model',p.model)}${fieldSelect('설치 공간','roomId',p.roomId,ROOMS)}
    ${fieldNum('정가','listPrice',p.listPrice)}${fieldNum('견적가','quotePrice',p.quotePrice)}${fieldNum('예상 구매가격','expectedPrice',p.expectedPrice)}${fieldNum('실제 구매가격','actualPrice',p.actualPrice)}${fieldNum('수량','quantity',p.quantity||1)}${fieldNum('캐시백','cashback',p.cashback)}${fieldNum('포인트 사용','pointsUsed',p.pointsUsed)}${fieldNum('사은품 환산금액','giftValue',p.giftValue)}
    <div class="field"><label>사은품 체감가 반영</label><select name="giftIncluded"><option value="false" ${!p.giftIncluded?'selected':''}>미포함</option><option value="true" ${p.giftIncluded?'selected':''}>포함</option></select></div>${fieldSelect('우선순위','priority',p.priority,PRIORITIES)}${fieldSelect('구매 상태','purchaseStatus',p.purchaseStatus,STATUSES)}${fieldSelect('설치 가능 상태','installStatus',p.installStatus,INSTALL_STATUSES)}
    ${fieldDate('구매 예정일','purchasePlanDate',p.purchasePlanDate)}${fieldDate('실제 구매일','purchaseDate',p.purchaseDate)}${fieldDate('배송 예정일','deliveryDate',p.deliveryDate)}${fieldDate('설치 예정일','installDate',p.installDate)}${fieldSelect('결제수단','paymentMethod',p.paymentMethod,PAYMENT_METHODS)}${fieldSelect('비용 부담','payerType',p.payerType,PAYER_TYPES)}${fieldNum('나 부담 %','mySharePercent',p.mySharePercent)}${fieldNum('배우자 부담 %','partnerSharePercent',p.partnerSharePercent)}
    ${fieldNum('가로 mm','widthMm',p.widthMm)}${fieldNum('세로/깊이 mm','depthMm',p.depthMm)}${fieldNum('높이 mm','heightMm',p.heightMm)}${fieldText('구매처','store',p.store)}${fieldText('제품 URL','url',p.url)}
    <div class="field full"><label>이미지 URL</label><input name="imageUrl" value="${p.image && !String(p.image).startsWith('data:') ? esc(p.image) : ''}" placeholder="https://..."></div><div class="field full"><label>제품 사진 직접 업로드</label><input id="productImageFile" type="file" accept="image/*"><small>업로드 파일이 있으면 이미지 URL보다 우선합니다. 작은 이미지 사용 권장.</small>${p.image?`<img src="${esc(p.image)}" style="width:130px;margin-top:8px;border-radius:12px">`:''}</div>
    <div class="field full"><label>메모</label><textarea name="memo">${esc(p.memo)}</textarea></div>
    <div class="field full"><div class="notice">계산 미리보기 · 예상 ${won(calcExpectedTotal(p))} / 실제 ${won(calcActualTotal(p))} / 체감 ${won(calcEffective(p))}</div></div>
    </div></div><div class="modal-foot">${ui.editingId?`<button type="button" class="btn danger" id="deleteProduct">삭제</button><button type="button" class="btn" id="duplicateProduct">복제</button>`:''}<button type="button" class="btn" data-close-modal>취소</button><button class="btn primary" type="submit">저장</button></div></form></div></div>`}
  function quoteModal(){const q=state.quotes.find(x=>x.id===ui.editingId)||{id:'',name:'',store:'',manager:'',date:'',productIds:[],normalPrice:0,discount:0,cardDiscount:0,points:0,cashback:0,gift:0,finalPrice:0,effectivePrice:0,memo:''};return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${ui.editingId?'견적 수정':'견적 등록'}</h3><button class="btn ghost" data-close-modal>✕</button></div><form id="quoteForm"><div class="modal-body"><div class="form-grid">${fieldText('견적명','name',q.name,true)}${fieldText('매장','store',q.store)}${fieldText('담당자','manager',q.manager)}${fieldDate('견적 날짜','date',q.date)}${fieldNum('정상가','normalPrice',q.normalPrice)}${fieldNum('전체 할인','discount',q.discount)}${fieldNum('카드 할인','cardDiscount',q.cardDiscount)}${fieldNum('포인트','points',q.points)}${fieldNum('캐시백','cashback',q.cashback)}${fieldNum('사은품 환산','gift',q.gift)}${fieldNum('최종 결제금액','finalPrice',q.finalPrice)}${fieldNum('체감 구매금액','effectivePrice',q.effectivePrice)}<div class="field full"><label>포함 제품</label><div class="grid" style="grid-template-columns:repeat(2,1fr)">${state.products.map(p=>`<label class="inline"><input type="checkbox" name="productIds" value="${p.id}" ${(q.productIds||[]).includes(p.id)?'checked':''}>${esc(p.name)}</label>`).join('')}</div></div><div class="field full"><label>메모</label><textarea name="memo">${esc(q.memo)}</textarea></div></div></div><div class="modal-foot">${ui.editingId?`<button type="button" class="btn danger" id="deleteQuote">삭제</button>`:''}<button type="button" class="btn" data-close-modal>취소</button><button class="btn primary" type="submit">저장</button></div></form></div></div>`}
  function simpleModal(){const d=ui.simple||{};return `<div class="modal-backdrop"><div class="modal" style="max-width:560px"><div class="modal-head"><h3>${esc(d.title)}</h3><button class="btn ghost" data-close-modal>✕</button></div><form id="simpleForm"><div class="modal-body">${d.html||''}</div><div class="modal-foot"><button type="button" class="btn" data-close-modal>취소</button><button class="btn primary" type="submit">저장</button></div></form></div></div>`}
  function fieldText(label,name,value,req=false){return `<div class="field"><label>${label}${req?' *':''}</label><input name="${name}" value="${esc(value||'')}" ${req?'required':''}></div>`}
  function fieldNum(label,name,value){return `<div class="field"><label>${label}</label><input name="${name}" inputmode="numeric" type="number" min="0" value="${num(value)}"></div>`}
  function fieldDate(label,name,value){return `<div class="field"><label>${label}</label><input name="${name}" type="date" value="${esc(value||'')}"></div>`}
  function fieldSelect(label,name,value,options){return `<div class="field"><label>${label}</label><select name="${name}">${options.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></div>`}
  function blankProduct(){return {id:'',type:'가전',category:'TV',name:'',brand:'',model:'',image:'',url:'',store:'',roomId:'거실',listPrice:0,quotePrice:0,expectedPrice:0,actualPrice:0,quantity:1,storeDiscount:0,brandDiscount:0,eventDiscount:0,cardDiscount:0,couponDiscount:0,pointsUsed:0,cashback:0,giftValue:0,giftIncluded:false,priority:'2순위 구매 예정',purchaseStatus:'후보 조사',purchasePlanDate:'',purchaseDate:'',deliveryDate:'',installDate:'',deliveryDone:false,installDone:false,paymentMethod:'미지정',cardCompany:'',cardName:'',installmentMonths:0,payerType:'미지정',mySharePercent:50,partnerSharePercent:50,widthMm:0,depthMm:0,heightMm:0,installStatus:'실측 필요',favorite:false,memo:'',isSample:false}}

  function bindView(){
    document.querySelectorAll('.edit-product').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.id)));
    const si=document.getElementById('searchInput'); if(si)si.addEventListener('input',e=>{ui.search=e.target.value;render()});
    document.getElementById('typeFilter')?.addEventListener('change',e=>{ui.typeFilter=e.target.value;render()}); document.getElementById('statusFilter')?.addEventListener('change',e=>{ui.statusFilter=e.target.value;render()});
    document.getElementById('addCompare')?.addEventListener('click',()=>{const id=document.getElementById('comparePicker').value;if(id&&ui.selectedCompare.length<5){ui.selectedCompare.push(id);render()}});document.querySelectorAll('.remove-compare').forEach(b=>b.addEventListener('click',()=>{ui.selectedCompare=ui.selectedCompare.filter(x=>x!==b.dataset.id);render()}));
    document.getElementById('addQuote')?.addEventListener('click',()=>openQuote());document.querySelectorAll('.edit-quote').forEach(b=>b.addEventListener('click',()=>openQuote(b.dataset.id)));
    document.getElementById('addChecklist')?.addEventListener('click',()=>openSimple('할 일 추가',`${fieldText('할 일','title','',true)}${fieldSelect('공간','roomId','거실',ROOMS)}`,'checklist'));document.querySelectorAll('.check-toggle').forEach(c=>c.addEventListener('change',()=>{const i=state.checklist.find(x=>x.id===c.dataset.id);if(i)i.completed=c.checked;commit()}));document.querySelectorAll('.delete-check').forEach(b=>b.addEventListener('click',()=>{state.checklist=state.checklist.filter(x=>x.id!==b.dataset.id);commit('삭제됨')}));
    document.getElementById('addSchedule')?.addEventListener('click',()=>openSimple('일정 추가',`${fieldSelect('유형','type','배송',['견적 방문','구매 예정','결제','배송','설치','교환','AS'])}${fieldText('제목','title','',true)}${fieldDate('날짜','date','')}<div class="field"><label>메모</label><textarea name="memo"></textarea></div>`,'schedule'));document.querySelectorAll('.delete-schedule').forEach(b=>b.addEventListener('click',()=>{state.schedule=state.schedule.filter(x=>x.id!==b.dataset.id);commit('일정 삭제됨')}));
    document.getElementById('addWish')?.addEventListener('click',()=>openSimple('위시리스트 추가',`${fieldText('제품명','name','',true)}${fieldNum('희망가격','targetPrice',0)}<div class="field"><label>메모</label><textarea name="memo"></textarea></div>`,'wishlist'));document.querySelectorAll('.delete-wish').forEach(b=>b.addEventListener('click',()=>{state.wishlist=state.wishlist.filter(x=>x.id!==b.dataset.id);commit('삭제됨')}));
    document.getElementById('saveSettings')?.addEventListener('click',()=>{state.project.name=document.getElementById('projectName').value.trim()||'우리 신혼집';state.project.totalBudget=Math.max(0,num(document.getElementById('projectBudget').value));state.project.moveInDate=document.getElementById('moveInDate').value;commit('설정 저장됨')});
    document.getElementById('exportJson')?.addEventListener('click',exportJSON);document.getElementById('exportCsv')?.addEventListener('click',exportCSV);document.getElementById('importJson')?.addEventListener('change',importJSON);document.getElementById('removeSamples')?.addEventListener('click',()=>{state.products=state.products.filter(p=>!p.isSample);state.settings.sampleData=false;commit('예시 데이터 삭제됨')});document.getElementById('addCategory')?.addEventListener('click',()=>{const t=document.getElementById('catType').value;const c=document.getElementById('newCategory').value.trim();if(c&&!state.categories[t].includes(c)){state.categories[t].push(c);commit('카테고리 추가됨')}});document.querySelectorAll('.delete-cat').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.type,c=b.dataset.cat;if(c==='기타'){alert('기본 기타 카테고리는 유지합니다.');return}if(confirm(`'${c}' 카테고리를 삭제할까요?`)){state.categories[t]=state.categories[t].filter(x=>x!==c);commit('카테고리 삭제됨')}}));document.getElementById('resetAll')?.addEventListener('click',resetAll);
    bindFloorplan();bindModals();
  }

  function openProduct(id=null){ui.modal='product';ui.editingId=id;render()}
  function openQuote(id=null){ui.modal='quote';ui.editingId=id;render()}
  function openSimple(title,html,kind){ui.modal='simple';ui.editingId=null;ui.simple={title,html,kind};render()}

  function bindModals(){
    const pf=document.getElementById('productForm'); if(pf)pf.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(pf);let p=ui.editingId?{...state.products.find(x=>x.id===ui.editingId)}:blankProduct();Object.assign(p,Object.fromEntries(fd.entries())); if(fd.get('imageUrl')) p.image=String(fd.get('imageUrl')).trim(); delete p.imageUrl; ['listPrice','quotePrice','expectedPrice','actualPrice','quantity','cashback','pointsUsed','giftValue','mySharePercent','partnerSharePercent','widthMm','depthMm','heightMm'].forEach(k=>p[k]=num(p[k]));p.giftIncluded=fd.get('giftIncluded')==='true';if(p.payerType==='공동 부담'&&Math.round(p.mySharePercent+p.partnerSharePercent)!==100){alert('공동 부담 비율의 합은 반드시 100%여야 합니다.');return}const file=document.getElementById('productImageFile')?.files?.[0];if(file){if(file.size>1.5*1024*1024){alert('브라우저 저장공간을 위해 1.5MB 이하 이미지를 권장합니다.');return}p.image=await fileToDataURL(file)}if(!p.id)p.id=uid();if(ui.editingId)state.products=state.products.map(x=>x.id===p.id?p:x);else state.products.push(p);ui.modal=null;ui.editingId=null;commit('제품 저장됨')});
    document.getElementById('deleteProduct')?.addEventListener('click',()=>{if(confirm('이 제품을 삭제하시겠습니까?')){const id=ui.editingId;state.products=state.products.filter(x=>x.id!==id);state.floorPlanItems=state.floorPlanItems.filter(x=>x.productId!==id);ui.selectedCompare=ui.selectedCompare.filter(x=>x!==id);ui.modal=null;commit('제품 삭제됨')}});document.getElementById('duplicateProduct')?.addEventListener('click',()=>{const p=state.products.find(x=>x.id===ui.editingId);if(p){state.products.push({...p,id:uid(),name:p.name+' 복사본'});ui.modal=null;commit('제품 복제됨')}});
    const qf=document.getElementById('quoteForm');if(qf)qf.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(qf);let q=ui.editingId?{...state.quotes.find(x=>x.id===ui.editingId)}:{id:uid()};Object.assign(q,Object.fromEntries(fd.entries()));q.productIds=fd.getAll('productIds');['normalPrice','discount','cardDiscount','points','cashback','gift','finalPrice','effectivePrice'].forEach(k=>q[k]=num(q[k]));if(!q.finalPrice)q.finalPrice=Math.max(0,q.normalPrice-q.discount-q.cardDiscount-q.points);if(!q.effectivePrice)q.effectivePrice=Math.max(0,q.finalPrice-q.cashback-q.gift);if(ui.editingId)state.quotes=state.quotes.map(x=>x.id===q.id?q:x);else state.quotes.push(q);ui.modal=null;ui.editingId=null;commit('견적 저장됨')});document.getElementById('deleteQuote')?.addEventListener('click',()=>{if(confirm('이 견적을 삭제하시겠습니까?')){state.quotes=state.quotes.filter(x=>x.id!==ui.editingId);ui.modal=null;commit('견적 삭제됨')}});
    const sf=document.getElementById('simpleForm');if(sf)sf.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(sf);const d=Object.fromEntries(fd.entries());if(ui.simple.kind==='checklist')state.checklist.push({id:uid(),title:d.title,roomId:d.roomId,productId:'',completed:false});if(ui.simple.kind==='schedule')state.schedule.push({id:uid(),type:d.type,title:d.title,date:d.date,memo:d.memo||'',productId:''});if(ui.simple.kind==='wishlist')state.wishlist.push({id:uid(),name:d.name,targetPrice:num(d.targetPrice),memo:d.memo||''});ui.modal=null;commit('저장됨')});
  }

  function bindFloorplan(){
    document.querySelectorAll('.add-floor-product').forEach(b=>b.addEventListener('click',()=>{const p=state.products.find(x=>x.id===b.dataset.id);const scaleW=p?.widthMm?Math.min(.28,Math.max(.09,p.widthMm/5800)):.16;const scaleH=p?.depthMm?Math.min(.20,Math.max(.05,p.depthMm/7470)):.07;const item={id:uid(),productId:b.dataset.id,roomId:p?.roomId||'',x:.5,y:.5,width:scaleW,height:scaleH,rotation:0};state.floorPlanItems.push(item);ui.selectedFloorItem=item.id;commit('평면도에 배치됨')}));
    document.querySelectorAll('.floor-item').forEach(el=>{el.addEventListener('pointerdown',e=>{e.preventDefault();ui.selectedFloorItem=el.dataset.floorId;const item=state.floorPlanItems.find(x=>x.id===el.dataset.floorId);const canvas=document.getElementById('floorCanvas');const rect=canvas.getBoundingClientRect();const move=ev=>{item.x=Math.max(0,Math.min(1,(ev.clientX-rect.left)/rect.width));item.y=Math.max(0,Math.min(1,(ev.clientY-rect.top)/rect.height));el.style.left=(item.x*100)+'%';el.style.top=(item.y*100)+'%'};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);saveState();render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})})});
    document.getElementById('rotateFloor')?.addEventListener('click',()=>{const i=state.floorPlanItems.find(x=>x.id===ui.selectedFloorItem);if(i){i.rotation=((i.rotation||0)+90)%360;commit('회전 저장됨')}});document.getElementById('removeFloor')?.addEventListener('click',()=>{state.floorPlanItems=state.floorPlanItems.filter(x=>x.id!==ui.selectedFloorItem);ui.selectedFloorItem=null;commit('배치 제거됨')});
  }

  function exportJSON(){download(`우리집준비노트-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json;charset=utf-8');toast('JSON 백업 생성됨')}
  function exportCSV(){const headers=['구분','카테고리','제품명','브랜드','모델명','예상가격','실제가격','체감가격','우선순위','구매상태','설치공간','비용부담','메모'];const rows=state.products.map(p=>[p.type,p.category,p.name,p.brand,p.model,calcExpectedTotal(p),calcActualTotal(p),calcEffective(p),p.priority,p.purchaseStatus,p.roomId,p.payerType,p.memo]);const csv='\ufeff'+[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');download(`우리집-제품목록-${new Date().toISOString().slice(0,10)}.csv`,csv,'text/csv;charset=utf-8');toast('CSV 생성됨')}
  function importJSON(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!parsed.project||!Array.isArray(parsed.products))throw new Error('형식 오류');if(confirm('현재 데이터를 백업 파일로 대체하시겠습니까?')){state=migrate(parsed);saveState();render();toast('백업 복구 완료')}}catch(err){alert('올바른 백업 JSON 파일이 아닙니다.')}};r.readAsText(f)}
  function resetAll(){if(!confirm('모든 제품, 예산, 일정 및 평면도 배치 데이터가 삭제됩니다. 계속할까요?'))return;if(!confirm('정말 초기화하시겠습니까? 이 작업은 되돌릴 수 없습니다.'))return;localStorage.removeItem(STORAGE_KEY);state=defaultState();saveState();render();toast('초기화 완료')}
  function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
  function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}

  render();
})();
